name: Deploy Platform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ---------------- FRONTEND ----------------

      - name: Build frontend image
        run: |
          docker build -t transcoding-frontend ./frontend

      - name: Tag frontend image
        run: |
          docker tag transcoding-frontend:latest \
          975049973618.dkr.ecr.us-east-1.amazonaws.com/transcoding-frontend:latest

      - name: Push frontend image
        run: |
          docker push 975049973618.dkr.ecr.us-east-1.amazonaws.com/transcoding-frontend:latest

      - name: Deploy frontend
        run: |
          aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER }} \
          --service ${{ secrets.ECS_FRONTEND_SERVICE }} \
          --force-new-deployment

      # ---------------- BACKEND API ----------------

      - name: Build API image
        run: |
          docker build -t transcoding-api ./backend

      - name: Tag API image
        run: |
          docker tag transcoding-api:latest \
          975049973618.dkr.ecr.us-east-1.amazonaws.com/transcoding-api:latest

      - name: Push API image
        run: |
          docker push 975049973618.dkr.ecr.us-east-1.amazonaws.com/transcoding-api:latest

      - name: Deploy API
        run: |
          aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER }} \
          --service ${{ secrets.ECS_API_SERVICE }} \
          --force-new-deployment
